### ISSUE TITLE
Error on /students page

### ISSUE THREAD

**Issue by robinmck11** [arunkal1/Attendance_Application#7]
To reproduce the error, delete the eng-16 group and then navigate to the /students page. In the seed file, you can add more students associated with other groups and the same issue occurs.

![screen shot 2018-10-11 at 11 47 28](https://user-images.githubusercontent.com/24536293/46799093-be13a580-cd4b-11e8-8b7a-b62e1f5e87e3.png)

**Comment by WMichael** [comment]
I can't seem to reproduce the error. I tried deleting that group but when I go to students I don't get any error.

It seems as though when you deleted eng-16 it somehow deleted eng-01 and on the students list would try to get the group name of an id that no longer exists.

**Comment by robinmck11** [comment]
I've changed group.rb and student.rb to enforce data integrity so I removed your solution that removed students in the controller.
