### ISSUE TITLE
New Student Form Issue

### ISSUE THREAD

**Issue by arunkal1** [arunkal1/Attendance_Application#8]
When creating a new student for a new group just created- when I leave the name blank rather than showing validation for 'please insert name' the page breaks and show the message I've screenshotted...
![screen shot 2018-10-11 at 13 44 26](https://user-images.githubusercontent.com/42513943/46805019-f91dd500-cd5b-11e8-8df9-0431b92b7a3e.png)

**Comment by arunkal1** [comment]
When I dont leave the name blank it works but when i miss out the name it breaks

**Comment by WMichael** [comment]
I found the problem, when the page refreshes to show the validation it doesn't pass the course list to the form. I fixed it now and will push to dev. Can you try it to see if it works for you.

**Comment by arunkal1** [comment]
Perfect works now. I'll style your validation messages
